package se.inera.fmu.domain.model.eavrop.note;

public enum NoteType {
	EAVROP,
	EAVROP_ASSIGNMENT_REJECTION,
	BOOKING_DEVIATION,
	BOOKING_DEVIATION_RESPONSE,
	DOCUMENT_REQUEST,
	APPROVAL,
	COMPENSATION_APPROVAL;
}
