package se.inera.fmu.domain.model.eavrop;

public enum EavropCompletedType {
	NOT_COMPLETED_NOT_APPROVED_OR_DEVIATED,
	NOT_COMPLETED_PENDING,
	COMPLETE_AND_APPROVED_FOR_COMPENSATION,
	COMPLETE_PENDING_COMPENSATION_APPROVAL;
}
